### ISSUE TITLE
add corresponding prometheus alerts for every postgres operator

### ISSUE THREAD

**Issue by y16144** [fi-ts/postgreslet#10]
- add prometheus alerts (attached the currently used yaml file)

```
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    release: prometheus
    role: alert-rules
  name: postgres-alert.rules
  namespace: monitoring
spec:
  groups:
  - name: postgres.rules
    rules:
    - alert: PostgreSQLMaxConnectionsReached
      expr: sum(pg_stat_activity_count) by (instance) >= sum(pg_settings_max_connections) by (instance) - sum(pg_settings_superuser_reserved_connections) by (instance)
      for: 1m
      labels:
        severity: critical
      annotations:
        summary: "{{ $labels.instance }} has maxed out Postgres connections."
        description: "{{ $labels.instance }} is exceeding the currently configured maximum Postgres connection limit (current value: {{ $value }}s). Services may be degraded - please take immediate action (you probably need to increase max_connections in the Docker image and re-deploy."

    - alert: PostgreSQLHighConnections
      expr: sum(pg_stat_activity_count) by (instance) > (sum(pg_settings_max_connections) by (instance) - sum(pg_settings_superuser_reserved_connections) by (instance)) * 0.8
      for: 10m
      labels:
        severity: critical
      annotations:
        summary: "{{ $labels.instance }} is over 80% of max Postgres connections."
        description: "{{ $labels.instance }} is exceeding 80% of the currently configured maximum Postgres connection limit (current value: {{ $value }}s). Please check utilization graphs and confirm if this is normal service growth, abuse or an otherwise temporary condition or if new resources need to be provisioned (or the limits increased, which is mostly likely)."

    - alert: PostgreSQLDown
      expr: pg_up != 1
      for: 1m
      labels:
        severity: critical
      annotations:
        summary: "PostgreSQL is not processing queries: {{ $labels.instance }}"
        description: "{{ $labels.instance }} is rejecting query requests from the exporter, and thus probably not allowing DNS requests to work either. User services should not be effected provided at least 1 node is still alive."

    - alert: PostgreSQLSlowQueries
      expr: avg(rate(pg_stat_activity_max_tx_duration{datname!~"template.*"}[2m])) by (datname) > 2 * 60
      for: 2m
      labels:
        severity: warning
      annotations:
        summary: "PostgreSQL high number of slow on {{ $labels.cluster }} for database {{ $labels.datname }} "
        description: "PostgreSQL high number of slow queries {{ $labels.cluster }} for database {{ $labels.datname }} with a value of {{ $value }} "

    - alert: PostgreSQLQPS
      expr: avg(irate(pg_stat_database_xact_commit{datname!~"template.*"}[5m]) + irate(pg_stat_database_xact_rollback{datname!~"template.*"}[5m])) by (datname) > 10000
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "PostgreSQL high number of queries per second {{ $labels.cluster }} for database {{ $labels.datname }}"
        description: "PostgreSQL high number of queries per second on {{ $labels.cluster }} for database {{ $labels.datname }} with a value of {{ $value }}"

    - alert: PostgreSQLCacheHitRatio
      expr: avg(rate(pg_stat_database_blks_hit{datname!~"template.*"}[5m]) / (rate(pg_stat_database_blks_hit{datname!~"template.*"}[5m]) + rate(pg_stat_database_blks_read{datname!~"template.*"}[5m]))) by (datname) < 0.98
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "PostgreSQL low cache hit rate on {{ $labels.cluster }} for database {{ $labels.datname }}"
        description: "PostgreSQL low on cache hit rate on {{ $labels.cluster }} for database {{ $labels.datname }} with a value of {{ $value }}"
    
    - alert: PostgreSQL_PanicError
      expr: >-
        sum(increase(pg_logs_total{severity="PANIC"}[5m])) by (server) > 0
      labels:
        severity: panic
        job: PostgreSQL_PanicError
      annotations:
        message: "PostgreSQL has logged PANIC errors "
        description: >-
          Server {{ $labels.pod }} has logged {{ $value }} PANIC errors in
          the last five minutes. Please take a look at the log files to find
          out what's going on.

    - alert: PostgreSQL_OtherError
      expr: >-
        sum(rate(pg_errors_total{type="other"}[5m])) by (server) > 0.5
      labels:
        severity: warning
        job: PostgreSQL_OtherError
      annotations:
        message: "PostgreSQL is showing a high rate of 'other' errors "
        description: >-
          Server {{ $labels.pod }} is logging {{ $value | printf "%.1f" }}
          'other' errors per second.

    - alert: PostgreSQL_FatalError
      expr: >-
        sum(increase(pg_logs_total{severity="FATAL"}[5m])) by (server) > 0
      labels:
        job: PostgreSQL_FatalError
        severity: critical
      annotations:
        message: "PostgreSQL has logged FATAL errors "
        description: >-
          Server {{ $labels.pod }} has logged {{ $value }} FATAL errors in
          the last five minutes. Please take a look at the log files to find
          out what's going on.

    - alert: PostgreSQL_CommitRateTooLow
      expr: >-
        rate(pg_stat_database_xact_commit[5m]) < 100
      labels:
        job: PostgreSQL_CommitRateTooLow
        severity: warning
      annotations:
        message: "PostgreSQL absolute COMMIT rate is low "
        description: >-
          Server {{ $labels.pod }} is experiencing an implausibly low
          COMMIT rate of {{ $value | printf "%.0f" }} per second. 

    - alert: PostgreSQL_SlowQueries
      expr: >-
        avg(avg_over_time(pg_stat_activity_max_tx_duration[2m])) by (server, datname) > 120
      labels:
        severity: warning
        job: PostgreSQL_SlowQueries
      annotations:
        message: "PostgreSQL has a high number of slow queries "
        description: >-
          Server {{ $labels.pod }} has a high number of slow queries for
          database {{ $labels.datname }} with a value of {{ $value | printf "%.2f" }}.
          
    - alert: PostgreSQL_RollbackRateTooHigh
      expr: >-
        round(increase(pg_stat_database_xact_rollback[10m]) / increase(pg_stat_database_xact_commit[10m]) * 10000) / 100 >= 5.00
      labels:
        job: PostgreSQL_RollbackRateTooHigh
        severity: warning
      annotations:
        message: "PostgreSQL relative ROLLBACK rate is high "
        description: >-
          Server {{ $labels.pod }} is experiencing an implausibly high
          ROLLBACK/COMMIT rate of {{ $value | printf "%.2f" }}. 



```
