### ISSUE TITLE
Add additional config params for patroni

### ISSUE THREAD

**Issue by eberlep** [fi-ts/postgreslet#228]
```
apiVersion: "acid.zalan.do/v1"
kind: postgresql
spec:
  patroni:
    ttl: "{{patroni.ttl | default (30)}}"
    loop_wait: &loop_wait "{{patroni.loop_wait | default (10)}}"
    retry_timeout: "{{patroni.retry_timeout | default (10)}}"
```
