### ISSUE TITLE
Configured PostgresVersions not working properly

### ISSUE THREAD

**Issue by eberlep** [fi-ts/postgreslet#230]
Configured in Dev:
```yaml
  postgres:
    versions:
      - version: 11
        expirationDate: "2022-01-01T00:00:00Z"
      - version: 12
      - version: 13
```
```bash
 ~ $ cloudctl postgres version
VERSION EXPIRATIONDATE           
11      2022-01-01T00:00:00.000Z
12      never                   
13      never
```

But when trying to use it:
```bash
 ~ $ cloudctl postgres create --description test2 --partition nbg-w8101 --project b621eb99-4888-4911-93fc-95854fc030e8 --version 11 --backup-config c4f0c102-7053-4976-bf6a-1e73f26b2a18
Error: [PUT /v1/database/postgres][500] createPostgres default  Postgres.database.fits.cloud "48d4b0c1-d2dc-4e98-88ce-eb5930889fd6" is invalid: spec.version: Unsupported value: "11": supported values: "12" (500)
```

**Comment by eberlep** [comment]
The problem seems to be [our CRD](https://github.com/fi-ts/postgreslet/blob/main/config/crd/bases/database.fits.cloud_postgres.yaml#L119):
```yaml
              version:
                default: "12"
                description: Version is the version of Postgre-as-a-Service
                enum:
                - "12"
                type: string
```
