### ISSUE TITLE
Enable sync mode

### ISSUE THREAD

**Issue by eberlep** [fi-ts/postgreslet#244]
```yaml
 patroni:
    initdb:
      data-checksums: "true"
      encoding: UTF8
      locale: en_US.UTF-8
    loop_wait: 10
    maximum_lag_on_failover: 33554432
    retry_timeout: 60
    synchronous_mode: true # required?
    synchronous_mode_strict: false # required?
    ttl: 130 # required?
  ```

Double check which ones are really neccessary to enable sync mode.
