### ISSUE TITLE
Enable Audit Logs (via pgaudit)

### ISSUE THREAD

**Issue by eberlep** [fi-ts/postgreslet#273]
e.g. like this:

```yaml
postgresql:
  parameters:
    shared_preload_libraries: "pgaudit"
    synchronous_commit: "off"  # do we really need that here?
    pgaudit.log_catalog: "off"
    pgaudit.log: "ddl"
    pgaudit.log_relation: "on"
    pgaudit.log_parameter: "on"
```
