### ISSUE TITLE
Add Network Policies

### ISSUE THREAD

**Issue by risonjic** [fi-ts/postgreslet#319]
The network segmentation between Pods within the Kubernetes database namespaces is insufficient due to
missing Network Policies.

**Comment by eberlep** [comment]
I think we will only need to handle `ingresss`, not `egress`.

And we will probably need an `ipBlock` (for the requests to the database port from the load balancer) and a `namespaceSelector` (for access to patroni from within the same namespace)

**Comment by eberlep** [comment]
```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: egress-allow-postgres
spec:
  podSelector: 
    matchLabels:
      application: spilo
      postgres.database.fits.cloud/tenant: Ft
  egress:
  # Postgres Cluster
  - to:
    - podSelector: 
        matchLabels:
          application: spilo
          postgres.database.fits.cloud/tenant: Ft
  # CoreDNS
  - to:
    - namespaceSelector:
        matchLabels:
          gardener.cloud/purpose: kube-system
      podSelector:
        matchLabels:
          k8s-app: kube-dns
  # etcd
  - to:
    - ipBlock:
        cidr: 0.0.0.0/0
    ports:
    - port: 2379
      protocol: TCP
  # S3 (Backup)
  - to:
    - ipBlock:
        cidr: 0.0.0.0/0
    ports:
    - port: 443
      protocol: TCP
    - port: 80
      protocol: TCP
    # TODO standby -> primary
  policyTypes:
  - Egress
```
