### ISSUE TITLE
Make Managed Postgres Databases Accessible

### ISSUE THREAD

**Issue by eberlep** [fi-ts/postgreslet#70]
The only purpose of having a database is, you know, storing data in it. To be able to do so, the customer needs to know how he or she can access it. This can be broken down into three subfeatures:
 * (Create a load balancer programmatically?)
 1. Calculate a free port
 2. Create a `Service` of type `LoadBalancer` by using the port we just calculated
 3. Update the corresponding `postgres` resource in the control plane cluster with the the routable socket (aka load balancer ip + service port)

## Calculate Free Port

One discussed solution was to define a fix range of ports for use with postgres databases and create a list of usable ports from that range. When calculating a free port, one could retrieve a list of all existing postgres services that were already created by the postgreslet (e.g. by using labels), and remove them from that list of usable ports. The result would be a list of ports that are still free to use. Simply pick one from that list and use it for a new service.

## Create a `Service` of type `LoadBalancer`

A LoadBalancer IP per service cluster has to be reserved via `cloudctl` and/or helm, in a way that several services can make use of that same ip (TODO: clarify with @y16144 ). When this is done, `Service` templates similar to [here](https://git.f-i-ts.de/cloud-services/products/postgresql/-/blob/develop/roles/postgresql-db/templates/postgresql-db-svc.yaml.j2) and [here](https://git.f-i-ts.de/cloud-services/products/postgresql/-/blob/develop/roles/postgresql-db/templates/postgresql-db-svc-lbsr.yaml.j2) can be used to create the service:

```yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: spilo
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  labels:
    application: spilo
    cluster-name: {{ main.teamid }}-{{ main.name }}
    spilo-role: master
    team: {{ main.teamid }}
  name: {{ main.teamid }}-{{ main.name }}-{{ ipsvc.ipdesc }}
  namespace: {{ operator_config.namespace }}
spec:
  loadBalancerSourceRanges: {{ ipsvc.loadBalancerSourceRanges }}
  ports:
  - name: postgresql
    port: {{ ipsvc.port }}
    protocol: TCP
    targetPort: 5432
  selector:
    application: spilo
    cluster-name: {{ main.teamid }}-{{ main.name }}
    spilo-role: master
  sessionAffinity: None
  type: LoadBalancer
  loadBalancerIP: {{ ipsvc.loadBalancerIP }}
```

## Update the corresponding `postgres` Resource

To make the ip and port visible to the user via `cloudctl`, der `StatusReconciler` should update the corresponding `postgres` custom resource in the control cluster. At this point, both values should be known.
