### ISSUE TITLE
Provide Credentials for Created Databases

### ISSUE THREAD

**Issue by eberlep** [fi-ts/postgreslet#93]
When the operator creates a new postgres cluster, it also creates at laest one admin account (`postgres` is the default name).

As the user does not have access to the service cluster, we need to copy those credentials to the control plance cluster so they can be read by the cloud-api / cloudctl tool.

To keep it simple at first but still allow different types of credentials in the future, we begin with **one secret per postgres cluster** (which contains _all_ the accounts of that database cluster) by the name `<TEAMID>-<DATABASE_NAME>-passwords`, where the datbase user's name is the key and the corresponding password is the value, e.g.:

```yaml
apiVersion: v1
data:
  postgres: SGpESnpRMTRnbmRIb1NlOUZDaFI2S2QzZnFXODVmUzFaaUVieGYxRHFMTkRjanh1YldoQkdQU29aUmNidXF5Qg==
  standby: U3RSWktGVFAzNVROanYyOWNZQ2ZUMzU0U3lmQXJhUWtJbTNKRjZZdDFqUUM3T1k3dDFzQVFsclQwTlkwZjJJcA==
kind: Secret
metadata:
  name: projectida-fb2790081310440fbd78-passwords
  namespace: pgaas
type: Opaque
```

This way, we can add other types of credentials in the future by using a different secret (with a different format) to store them.

To find all accounts to a postgres cluster, we should probably use the proper label selector:

```yaml
  labels:
    application: spilo
    cluster-name: projectida-fb2790081310440fbd78
    team: projectida
```

We can then add each `username`:`password` pair to our new secret in the control plane.
